[ADD] push mirror job

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -11,23 +11,25 @@ env:
 
 jobs:
   check_coding_style:
-      runs-on: ubuntu-latest
-      container:
-        image: ghcr.io/epitech/coding-style-checker:latest
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
 
-      steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      - name: Run coding style checker
-        run: |
-          check.sh $(pwd) $(pwd) 2>&1 | tee coding_style_reports.log
-          cat coding_style_reports.log
-        id: check_coding_style_output
+    - name: Run coding style checker
+      id: check_coding_style_output
+      run: |
+        check.sh $(pwd) $(pwd) 2>&1 | tee coding_style_reports.log
+        echo "::set-output name=number_of_errors::$(grep -c 'Error' coding_style_reports.log)"
+        cat coding_style_reports.log
 
-      - name: Fail if there are any coding style errors
-        if: steps.check_coding_style_output.outputs.number_of_errors > 0
-        run: exit 1
+    - name: Fail if there are any coding style errors
+      if: steps.check_coding_style_output.outputs.number_of_errors > 0
+      run: exit 1
+
 
   check_program_compilation:
     runs-on: ubuntu-latest
@@ -76,6 +78,6 @@ jobs:
       - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url:
-            MIRROR_URL
+            ${{ env.MIRROR_URL }}
           ssh_private_key:
             ${{ secrets.GIT_SSH_PRIVATE_KEY }}
