[TEST]

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -5,6 +5,10 @@ on:
     branches:
       - main
 
+env:
+  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-BDX-2-1-chocolatine-tom.bouisset.git
+  EXECUTABLES: pushswap,antman/antman,giantman/giantman,mysh,bsq
+
 jobs:
   check_coding_style:
       runs-on: ubuntu-latest
@@ -26,21 +30,30 @@ jobs:
         if: steps.check_coding_style_output.outputs.number_of_errors > 0
         run: exit 1
 
-  run-make-command:
+  check_program_compilation:
     runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker
 
     steps:
-      - name: checkout source repository
-        uses: actions/checkout@v2
-        with:
-          repository: EpitechPromo2027/B-CPE-110-BDX-1-1-BSQ-tom.bouisset
-          token: ${{ secrets.PAT }}
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      - name: Setup environment
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y build-essential
+    - name: Run make command with 2 minutes timeout
+      run: timeout 2m make
 
-      - name: Run make Command
-        run: |
-          make
+    - name: Run make clean
+      run: make clean
+
+    - name: Check executables
+      run: |
+        for executable in ${EXECUTABLES//,/ }; do
+          if [[ ! -x "$executable" ]]; then
+            echo "$executable not found or not executable"
+            exit 1
+          else
+            echo "$executable is found and executable"
+          fi
+        done
+
+          
